import React from 'react'
import type { Metadata } from 'next'
import { MetadataLabel } from '@sentinel/ui'

export const metadata: Metadata = {
  title: 'Privacy Policy',
}

const sections = [
  {
    heading: '1. URLs you scan',
    body: 'URLs submitted to the scanner are used only to perform the scan you requested. They are processed in memory for the duration of the request and are not stored, logged to a database, or tied to your identity.',
  },
  {
    heading: '2. What we collect',
    body: 'LinkSentinel does not require an account and sets no tracking cookies. Standard, short-lived server logs (IP address, timestamp, user agent) may exist for abuse prevention and are not used for profiling.',
  },
  {
    heading: '3. Third parties',
    body: 'Scan results are generated by LinkSentinel directly. Submitted URLs are not sold, shared, or forwarded to third-party data brokers or advertising networks.',
  },
  {
    heading: '4. Requests made on your behalf',
    body: 'When you scan a URL, LinkSentinel contacts that site from its own servers using read-only requests. The target site sees the scanner, not you.',
  },
  {
    heading: '5. Contact',
    body: 'Privacy questions or removal requests can be sent through the contact form on the portfolio site linked in the footer.',
  },
]

export default function PrivacyPage() {
  return (
    <section className="section-block-tight">
      <div className="sheet max-w-3xl">
        <div className="anim-fade flex flex-wrap items-center justify-between gap-3 border-b border-[color:var(--border)] pb-4">
          <MetadataLabel>Legal — Privacy Policy</MetadataLabel>
          <MetadataLabel plain>Effective 2026-06-11</MetadataLabel>
        </div>

        <h1 className="anim-rise display-title mt-10">Privacy Policy</h1>

        <div className="anim-rise mt-10 grid gap-8" style={{ animationDelay: '0.15s' }}>
          {sections.map((section) => (
            <div
              key={section.heading}
              className="border-t border-[color:var(--border)] pt-5"
            >
              <h2 className="heading-md">{section.heading}</h2>
              <p className="copy-sm mt-3">{section.body}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
